name: CI Template

on:
    workflow_call:
        inputs:
            enviorment:
                description: "What is You enviorment"
                required: true
                type: string


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Running..
              run: echo "I am running the build action in ${{github.event.inputs.enviorment}}"